export enum ESortFlightBy {
    DESC_PRICE = "DESC_PRICE",
    ASC_PRICE = "ASC_PRICE",
    DESC_DEPARTURE_TIME = "DESC_DEPARTURE_TIME",
    ASC_DEPARTURE_TIME = "ASC_DEPARTURE_TIME",
    DESC_DURATION = "DESC_DURATION",
    ASC_DURATION = "ASC_DURATION",
}

export enum EFlightStatus {
    DONE = "DONE",
    ACTIVE = "ACTIVE",
    CANCELLED = "CANCELLED",
}